---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dev.okteto.com/auto-ingress: "true"
  name: keys-app-front
  labels:
    project: keys-app-front

spec:  
  selector:
    project: keys-app-front
    
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keys-app-front  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: keys-app-front
    spec:
      containers:
        - name: keys-app-front
          image: mobydigital/keys-app-front:tagname
          imagePullPolicy: Always
          #volumeMounts:
          #  - name: landing-tls-vol
          #    mountPath: /etc/nginx/cert
          #    readOnly: true
          #  - name: landing-conf-vol
          #    subPath: extras.conf
          #    mountPath: /etc/nginx/extras.conf
          #  - name: landing-conf-vol
          #    subPath: default.conf
          #    mountPath: /etc/nginx/conf.d/default.conf
          ports:
            - containerPort: 80
      # volumes:
      #   - name: landing-tls-vol
      #     secret:
      #       secretName: landing-secret
      #   - name: landing-conf-vol
      #     configMap:
      #       name: keys-app-front-cm
      #       items:
      #         - key: extras.conf
      #           path: extras.conf
      #         - key: default.conf
      #           path: default.conf
