on: [push]

name: okteto

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/actions/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/actions/namespace@master
      with:
        namespace: herattis
    
    - uses: actions/checkout@v2
    
    - name: "Build and Publish"
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: mobydigital/keys-app-front 
        tags: ${{ github.sha }}
        workdir: client/

    - name: "Deploy"
      uses: okteto/actions/deploy@master
      with:
        namespace: herattis
        manifest: client/k8s.yml
        tag: keys-app-front:${{ github.sha }}
        waitOn: deployment/keys-app-front
        registry: mobydigital
