on:
  push:
    branches:
      - master

name: okteto

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/actions/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/actions/namespace@master
      with:
        namespace: herattis
    
    - uses: actions/checkout@master
    
    - name: "Build and Publish"
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: mobydigital/keys-app-front 
        tags: ${{ github.sha }}
        workdir: client/

    - name: "Image Tag Change"
      run: |
        sed -e "s/IMAGETAG/${{ github.sha }}/g" -i client/k8s.yml

    - name: "Deploy"
      uses: okteto/actions/apply@master
      with:
        namespace: herattis
        manifest: client/k8s.yml
