on:
  push:
    branches:
      - master

name: okteto

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/actions/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/actions/namespace@master
      with:
        namespace: herattis
    
    - uses: actions/checkout@master
    
    - name: "Build and Publish"
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: mobydigital/keys-app-front 
        tags: latest
        workdir: client/

    - name: "Apply K8S Deployment changes"
      uses: okteto/actions/apply@master
      with:
        namespace: herattis
        manifest: client/k8s.yml

    - name: "Push changes"
      uses: okteto/actions/push@master
      with:
        namespace: herattis
        name: keys-app-front
        manifest: client/k8s.yml
